### ISSUE TITLE
iOS 10

### ISSUE THREAD

**Issue by PierreScerri** [gurbyz/custom-cards-lovelace#11] opened 2019-02-18 11:48 UTC
**Which card does give you issues?**
power-wheel-card

**Which version of HA do you use?**
0.87.1

**Which version of the card do you use?**
0.0.9

**Describe the bug**
The card gives 'Custom element doesn't exist: power-wheel card' on iPad 4 IOS 10.3.  Works on iOS 11 and macOS.

**Configuration of the card**
```
color_icons: true
grid_power_consumption_entity: sensor.import_power
grid_power_production_entity: sensor.export_power
home_icon: 'mdi:home-assistant'
power_decimals: 0
power_icon: 'mdi:transmission-tower'
solar_icon: 'mdi:solar-power'
solar_power_entity: sensor.sdm120power
title: Power Now
type: 'custom:power-wheel-card'

```

**Expected behavior**
To work on older iOS devices.

**Screenshots**
![img_2006](https://user-images.githubusercontent.com/34303331/52948948-3c77f800-337b-11e9-8c51-85f8d7d18857.PNG)

**Additional context**
This is the card in Safari:
![screen shot 2019-02-18 at 12 50 30](https://user-images.githubusercontent.com/34303331/52949191-d9d32c00-337b-11e9-9112-d0b14d993e5c.png)

**Comment by gurbyz** [comment] 2019-02-18 17:35
Ouch! That's difficult to reproduce for me, because I don't own an iPad with that version of iOS.

But could you try the dev version of the power-wheel-card that's currently in the dev branch? There are some changes since the stable version of 0.0.9. There is a small chance (if we have luck) that this will help.
https://github.com/gurbyz/custom-cards-lovelace/blob/dev/power-wheel-card/power-wheel-card.js
(don't forget to update the `?v=number` in ui-lovelace.yaml`)

If that doesn't help, please switch on the debug mode (only in 0.0.10 available) with `debug=true` and please send the complete response of the logs in development console. (I don't even know if there is a dev console on iPad... could be missing in the browser. Oops.)

**Comment by PierreScerri** [comment] 2019-02-19 11:57
Tried version 10 as you suggested.
This is the result on macos:

![screen shot 2019-02-19 at 12 48 30](https://user-images.githubusercontent.com/34303331/53013081-23d41480-3445-11e9-835e-8b009e59e540.png)

iPad remains the same. Note that the Grid icon is now working( 'transmission-tower') as I intended.

Don't know exactly how to use debug=true.

**Comment by gurbyz** [comment] 2019-02-19 19:06
The 3 errors are a bug in the 0.0.10-dev version. My mistake. Thx for testing. ;-) It's fixed now. You can grab the code again. (And don't forget to update the `?v=number` parameter again, otherwise you'll keep looking at a cached version.)

No luck on iPad 10.3 then. :-/ There was a small chance that 0.0.10-dev would help, since there are a few initializations fixed.

You can use `debug` as a normal card parameter in the yaml file. Just use `debug: true`. (I made a typo in my first comment there and used an `=`. It should be a `:`. Edited it later).

What it does, is putting some extra logs in the developer console of the browser. Hopefully there are some errors too. But the difficulty on your browser on the iPad is probably that there is no developer console to show the errors. Without any info on the actual errors, I can't think of how to fix your issue. If it is fixable anyway, because of the age of IOS10.3 (March 2017)...

**Comment by PierreScerri** [comment] 2019-03-12 14:04
I've had the same problem with some other cards too.

I got this suggestion from Thomas Loven:

"...You can tell the maintainers of the other cards that if they wish to support iOS before 11.1, the {...object} destructuring notation needs to be replaced with Object.assign()..."

His cards work now.

Hope that it may guide you to the source of the anomaly.

Thank you.

**Comment by gurbyz** [comment] 2019-03-13 15:07
In [this table](https://kangax.github.io/compat-table/es6/#test-destructuring,_assignment_rest) your iOS10.3 should be able to process the destructuring language construct. But I trust Thomas more than this table. ;-) So, let's give it a try.

I replaced the ES6 notation a couple of times. I had to do it carefully, because the `this = { ...that }` is also used sometimes to trigger the card to re-render.

Can you try the 0.0.12-dev version of the card? Please set `debug: true` as card parameter to be able to check if you use the new version. (Version number 0.0.12-dev should be displayed in the orange warning message in the card).

If it's not working, my options are very limited to solve this issue. I could be using more ES6 language constructs that weren't known in 2017. But please add a link to a fixed card of Thomas in that case.

**Comment by PierreScerri** [comment] 2019-03-13 15:15
This has resolved the issue.  The card works on all devices.
Should I keep the dev version installed?

**Comment by gurbyz** [comment] 2019-03-13 18:52
Okay, great! You can switch to version 0.0.12 on master. It's released just now.

For the hiding of the toggle button: I already planned to make the parameters for the *power view* also optional. Then the *energy view* should be present without the toggle button if you wouldn't specify parameters for one of the others views. But because the first versions of the card were based on the (required) *power view* and the card evolved from that, that will be a slightly bigger change for me. Don't expect it too soon. ;-)

**Closed by gurbyz** 2019-03-13 18:52 UTC

**Comment by PierreScerri** [comment] 2019-03-13 23:12
Excellent.  Thank you.
